packages:
  - "apps/*"
  - "packages/*"
  - "services/identity-service/web"
  - "services/usage-service/web"
  - "services/usage-service/web-mfe"
  - "services/billing-service/web"
  - "services/team-service/web"
  - "services/team-service/web-mfe"
  - "services/notification-service/web"
  - "services/notification-service"
