#!/usr/bin/env bash
# Start web-edge only on a fresh EC2 so ALB target group health checks pass (port 8888 /healthz).
# Invoked from Terraform user-data and safe to re-run (idempotent compose up).
#
# Required env:
#   AWS_REGION
#   ECR_REPOSITORY_PREFIX  — e.g. ai-api-usage-monitor (no registry host)
#   BOOTSTRAP_IMAGE_TAG    — image tag that exists in ECR (e.g. staging or last release sha)
# Optional:
#   DEPLOY_ROOT            — default /opt/ai-api-usage-monitor
#   WEB_EDGE_HOST_PORT     — default 8888 (must match alb_target_port)
#   COMPOSE_PROJECT_NAME   — default aio-bootstrap

set -euo pipefail

DEPLOY_ROOT="${DEPLOY_ROOT:-/opt/ai-api-usage-monitor}"
AWS_REGION="${AWS_REGION:?}"
ECR_REPOSITORY_PREFIX="${ECR_REPOSITORY_PREFIX:?}"
BOOTSTRAP_IMAGE_TAG="${BOOTSTRAP_IMAGE_TAG:?}"
WEB_EDGE_HOST_PORT="${WEB_EDGE_HOST_PORT:-8888}"
COMPOSE_PROJECT_NAME="${COMPOSE_PROJECT_NAME:-aio-bootstrap}"
COMPOSE_FILE="${COMPOSE_FILE:-docker-compose-prod.bootstrap.yml}"

if [[ ! -f "${DEPLOY_ROOT}/${COMPOSE_FILE}" ]]; then
  echo "Missing ${DEPLOY_ROOT}/${COMPOSE_FILE} — skip bootstrap (clone repo or copy compose file first)." >&2
  exit 0
fi

if [[ -f "${DEPLOY_ROOT}/.env.deploy" ]] && [[ -f /var/lib/ai-api-usage-monitor-deploy/last-success-sha ]]; then
  echo "Full deploy env present — skip bootstrap (ec2-boot-compose or SSM roll will run the stack)."
  exit 0
fi

ACCOUNT="$(aws sts get-caller-identity --query Account --output text)"
export ECR_IMAGE_PREFIX="${ACCOUNT}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPOSITORY_PREFIX}"
export IMAGE_TAG="$BOOTSTRAP_IMAGE_TAG"
export WEB_EDGE_HOST_PORT
export GATEWAY_SHARED_SECRET="${GATEWAY_SHARED_SECRET:-bootstrap-health-only}"

STATE_DIR="/var/lib/ai-api-usage-monitor-deploy"
mkdir -p "$STATE_DIR"
BOOT_ENV="${STATE_DIR}/bootstrap.env"
{
  echo "# Generated by ec2-bootstrap-health-edge.sh"
  echo "ECR_IMAGE_PREFIX=${ECR_IMAGE_PREFIX}"
  echo "IMAGE_TAG=${IMAGE_TAG}"
  echo "WEB_EDGE_HOST_PORT=${WEB_EDGE_HOST_PORT}"
  echo "WEB_EDGE_HEALTH_HOST_PORT=8080"
  echo "GATEWAY_SHARED_SECRET=${GATEWAY_SHARED_SECRET}"
} >"$BOOT_ENV"
chmod 600 "$BOOT_ENV"

REGISTRY="${ACCOUNT}.dkr.ecr.${AWS_REGION}.amazonaws.com"
aws ecr get-login-password --region "$AWS_REGION" | docker login --username AWS --password-stdin "$REGISTRY"

cd "$DEPLOY_ROOT"
docker compose -p "$COMPOSE_PROJECT_NAME" -f "$COMPOSE_FILE" --env-file "$BOOT_ENV" pull web-edge
docker compose -p "$COMPOSE_PROJECT_NAME" -f "$COMPOSE_FILE" --env-file "$BOOT_ENV" up -d --force-recreate

for ((i = 1; i <= 30; i++)); do
  if curl -fsS "http://127.0.0.1:${WEB_EDGE_HOST_PORT}/healthz" >/dev/null 2>&1; then
    echo "Bootstrap health OK (http://127.0.0.1:${WEB_EDGE_HOST_PORT}/healthz)"
    exit 0
  fi
  if curl -fsS "http://127.0.0.1:8080/healthz" >/dev/null 2>&1; then
    echo "Bootstrap health OK (http://127.0.0.1:8080/healthz)"
    exit 0
  fi
  sleep 2
done

echo "Bootstrap web-edge started but /healthz not ready yet (ALB may need a few more probes)." >&2
exit 0
