#!/usr/bin/env bash
# Idempotent RabbitMQ on the EC2 host (Docker). Invoked from Terraform user-data on first boot.
# Apps in docker-compose-prod.yml reach the broker via RABBITMQ_HOST=host.docker.internal.

set -euo pipefail

RABBITMQ_USER="${RABBITMQ_USER:-app}"
RABBITMQ_PASSWORD="${RABBITMQ_PASSWORD:?RABBITMQ_PASSWORD is required}"
CONTAINER_NAME="${RABBITMQ_CONTAINER_NAME:-aio-host-rabbitmq}"
IMAGE="${RABBITMQ_IMAGE:-rabbitmq:3-management-alpine}"
STATE_DIR="${DEPLOY_STATE_DIR:-/var/lib/ai-api-usage-monitor-deploy}"
HOST_BIND="${RABBITMQ_HOST_BIND:-127.0.0.1}"

mkdir -p "$STATE_DIR"
chmod 700 "$STATE_DIR"

write_terraform_rabbitmq_env() {
  cat >"${STATE_DIR}/terraform-rabbitmq.env" <<EOF
# Generated by install-ec2-rabbitmq.sh (Terraform user-data). Do not commit.
RABBITMQ_HOST=host.docker.internal
RABBITMQ_PORT=5672
RABBITMQ_USER=${RABBITMQ_USER}
RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
RABBITMQ_SSL_ENABLED=false
NOTIFICATION_RABBITMQ_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@host.docker.internal:5672/%2f
EOF
  chmod 600 "${STATE_DIR}/terraform-rabbitmq.env"
}

rabbitmq_container_healthy() {
  docker ps --format '{{.Names}}' | grep -qx "$CONTAINER_NAME" \
    && docker exec "$CONTAINER_NAME" rabbitmq-diagnostics -q ping >/dev/null 2>&1
}

start_rabbitmq() {
  docker rm -f "$CONTAINER_NAME" 2>/dev/null || true
  docker run -d --name "$CONTAINER_NAME" --restart unless-stopped \
    -p "${HOST_BIND}:5672:5672" \
    -p "${HOST_BIND}:15672:15672" \
    -e "RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}" \
    -e "RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}" \
    "$IMAGE"
  for ((i = 1; i <= 30; i++)); do
    if docker exec "$CONTAINER_NAME" rabbitmq-diagnostics -q ping >/dev/null 2>&1; then
      echo "RabbitMQ ready (${CONTAINER_NAME} on ${HOST_BIND}:5672)"
      return 0
    fi
    sleep 2
  done
  echo "ERROR: RabbitMQ health check timed out for ${CONTAINER_NAME}" >&2
  docker logs --tail 40 "$CONTAINER_NAME" 2>&1 || true
  return 1
}

write_terraform_rabbitmq_env

if rabbitmq_container_healthy; then
  echo "RabbitMQ container ${CONTAINER_NAME} already running"
  exit 0
fi

start_rabbitmq
