#!/usr/bin/env bash
# Run on the EC2 host (via SSM). Pulls ECR images and restarts the stack using `docker compose` (Compose v2 plugin).
# Compose file defaults to `docker-compose.prod.yml` (filename in repo root; not the legacy `docker-compose` CLI).
# Prerequisites: Docker, compose plugin, AWS CLI; repo at DEPLOY_ROOT; `.env.deploy` with secrets (not in git).
#
# Env (required unless noted):
#   IMAGE_TAG              — immutable tag (git sha) to deploy
# Optional:
#   DEPLOY_ROOT            — default /opt/ai-api-usage-monitor
#   ENV_DEPLOY_FILE        — default .env.deploy (relative to DEPLOY_ROOT or absolute)
#   ECR_REPOSITORY_PREFIX  — suffix after account ECR host when deriving ECR_IMAGE_PREFIX (default ai-api-usage-monitor)
#   DEPLOY_STATE_DIR       — unset: root → /var/lib/...; non-root → ~/.local/state/... (override anytime)
#   COMPOSE_FILE           — default compose file name docker-compose.prod.yml (passed to `docker compose -f`)
#   HEALTH_URL             — default http://127.0.0.1:8080/healthz (web-edge :8080 listener)
#   HEALTH_RETRIES         — default 30
#   HEALTH_INTERVAL_SEC    — default 2
#   AWS_REGION             — for `aws ecr get-login-password` (optional if already logged in to ECR)

set -euo pipefail

DEPLOY_ROOT="${DEPLOY_ROOT:-/opt/ai-api-usage-monitor}"
ENV_DEPLOY_FILE="${ENV_DEPLOY_FILE:-.env.deploy}"
ECR_REPOSITORY_PREFIX="${ECR_REPOSITORY_PREFIX:-ai-api-usage-monitor}"
if [[ -z "${DEPLOY_STATE_DIR:-}" ]]; then
  if [[ "$(id -u)" -eq 0 ]]; then
    DEPLOY_STATE_DIR="/var/lib/ai-api-usage-monitor-deploy"
  else
    DEPLOY_STATE_DIR="${XDG_STATE_HOME:-$HOME/.local/state}/ai-api-usage-monitor-deploy"
  fi
fi
COMPOSE_FILE="${COMPOSE_FILE:-docker-compose.prod.yml}"
HEALTH_URL="${HEALTH_URL:-http://127.0.0.1:8080/healthz}"
HEALTH_RETRIES="${HEALTH_RETRIES:-30}"
HEALTH_INTERVAL_SEC="${HEALTH_INTERVAL_SEC:-2}"
IMAGE_TAG="${IMAGE_TAG:?IMAGE_TAG is required}"

resolve_env_deploy_path() {
  if [[ "$ENV_DEPLOY_FILE" = /* ]]; then
    printf '%s' "$ENV_DEPLOY_FILE"
  else
    printf '%s' "${DEPLOY_ROOT%/}/$ENV_DEPLOY_FILE"
  fi
}

# SSM often runs as root while .env.deploy may be ec2-user-only (mode 600). Compose reads the file via
# internal tooling that can fail with "grep: .env.deploy: Permission denied" and leave variables blank.
ensure_env_deploy_readable() {
  local path="$1"
  if [[ ! -f "$path" ]]; then
    echo "Missing deploy env file: $path" >&2
    echo "Copy .env.deploy.example to .env.deploy on the host and fill secrets (see docs/aws-github-oidc-ecr-ssm.md)." >&2
    exit 1
  fi
  if [[ -r "$path" ]]; then
    return 0
  fi
  echo "Deploy env file not readable: $path" >&2
  if [[ "$(id -u)" -eq 0 ]]; then
    chown root:root "$path" 2>/dev/null || true
    chmod 600 "$path" 2>/dev/null || true
  elif command -v sudo >/dev/null 2>&1; then
    sudo chown root:root "$path"
    sudo chmod 600 "$path"
  fi
  if [[ ! -r "$path" ]]; then
    echo "Still cannot read $path — set mode 600 and owner readable by the deploy user (root for SSM)." >&2
    exit 1
  fi
}

# Merge static host secrets with the immutable tag from CI/SSM (IMAGE_TAG always wins).
write_compose_env_file() {
  local source_path="$1"
  local dest_path="$2"
  local tmp
  tmp="$(mktemp "${dest_path}.XXXXXX")"
  # shellcheck disable=SC1090
  set -a
  # shellcheck source=/dev/null
  source "$source_path"
  set +a
  export IMAGE_TAG
  if [[ -z "${ECR_IMAGE_PREFIX:-}" ]]; then
    if [[ -z "${AWS_REGION:-}" ]]; then
      echo "ECR_IMAGE_PREFIX is unset and AWS_REGION is missing — cannot derive registry." >&2
      exit 1
    fi
    local account
    account="$(aws sts get-caller-identity --query Account --output text)"
    export ECR_IMAGE_PREFIX="${account}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPOSITORY_PREFIX}"
    echo "Derived ECR_IMAGE_PREFIX=${ECR_IMAGE_PREFIX}"
  fi
  if [[ -z "${ECR_IMAGE_PREFIX//[[:space:]]/}" ]] || [[ -z "${IMAGE_TAG//[[:space:]]/}" ]]; then
    echo "ECR_IMAGE_PREFIX and IMAGE_TAG must be non-empty (got ECR_IMAGE_PREFIX='${ECR_IMAGE_PREFIX}' IMAGE_TAG='${IMAGE_TAG}')" >&2
    exit 1
  fi
  {
    echo "# Generated by on-instance-compose-roll.sh — do not commit"
    echo "IMAGE_TAG=${IMAGE_TAG}"
    echo "ECR_IMAGE_PREFIX=${ECR_IMAGE_PREFIX}"
    grep -v -E '^(IMAGE_TAG|ECR_IMAGE_PREFIX)=' "$source_path" || true
  } >"$tmp"
  chmod 600 "$tmp"
  mv -f "$tmp" "$dest_path"
}

compose_cmd() {
  docker compose -f "$COMPOSE_FILE" --env-file "$COMPOSE_ENV_FILE" "$@"
}

mkdir -p "$DEPLOY_STATE_DIR"
STATE_FILE="$DEPLOY_STATE_DIR/last-success-sha"
PREVIOUS_SHA=""
if [[ -f "$STATE_FILE" ]]; then
  PREVIOUS_SHA="$(cat "$STATE_FILE")"
fi

rollback() {
  if [[ -z "$PREVIOUS_SHA" ]]; then
    echo "Rollback skipped: no previous successful sha in $STATE_FILE" >&2
    return 1
  fi
  echo "Rolling back to IMAGE_TAG=$PREVIOUS_SHA"
  export IMAGE_TAG="$PREVIOUS_SHA"
  write_compose_env_file "$ENV_DEPLOY_SOURCE" "$COMPOSE_ENV_FILE"
  (cd "$DEPLOY_ROOT" && compose_cmd pull && compose_cmd up -d)
}

cd "$DEPLOY_ROOT"

ENV_DEPLOY_SOURCE="$(resolve_env_deploy_path)"
ensure_env_deploy_readable "$ENV_DEPLOY_SOURCE"
COMPOSE_ENV_FILE="${DEPLOY_STATE_DIR}/compose.env"
write_compose_env_file "$ENV_DEPLOY_SOURCE" "$COMPOSE_ENV_FILE"
export IMAGE_TAG ECR_IMAGE_PREFIX

if [[ -n "${AWS_REGION:-}" ]]; then
  ACCOUNT="$(aws sts get-caller-identity --query Account --output text)"
  REGISTRY="${ACCOUNT}.dkr.ecr.${AWS_REGION}.amazonaws.com"
  aws ecr get-login-password --region "$AWS_REGION" | docker login --username AWS --password-stdin "$REGISTRY"
fi

if ! compose_cmd pull; then
  echo "docker compose pull failed" >&2
  rollback || true
  exit 1
fi
if ! compose_cmd up -d; then
  echo "docker compose up failed" >&2
  rollback || true
  exit 1
fi

ok=false
for ((i = 1; i <= HEALTH_RETRIES; i++)); do
  if curl -fsS "$HEALTH_URL" >/dev/null; then
    ok=true
    break
  fi
  sleep "$HEALTH_INTERVAL_SEC"
done

if [[ "$ok" != true ]]; then
  echo "Health check failed after $HEALTH_RETRIES attempts ($HEALTH_URL)" >&2
  rollback || true
  exit 1
fi

printf '%s' "$IMAGE_TAG" > "$STATE_FILE"
echo "Deploy OK; recorded last-success-sha=$IMAGE_TAG"
